SELECT CHILD.ID
FROM ECOLI_DATA AS CHILD
JOIN ECOLI_DATA AS PARENT
ON CHILD.PARENT_ID = PARENT.ID
JOIN ECOLI_DATA AS GRAND
ON PARENT.PARENT_ID = GRAND.ID
WHERE GRAND.PARENT_ID IS NULL
ORDER BY CHILD.ID